/**
 * Serbian word lists for the adjective + animal name generator.
 *
 * Hand-curated, ekavian, stored in Latin script (Cyrillic is derived at
 * runtime). Candidates were drawn from Wiktionary `Category:sh:Animals`
 * (CC BY-SA) and checked against the srLex 1.3 inflectional lexicon
 * (CC BY-SA 4.0, CLARIN.SI, http://hdl.handle.net/11356/1233) with
 * `scripts/verify-sr-words.ts`.
 *
 * Adjectives agree with the noun's grammatical gender, so each one carries its
 * definite nominative singular form for every gender: brzi vuk, brza lisica,
 * brzo pile. Adjectives are positive or neutral so no pair reads as an insult.
 */

export type Gender = 'm' | 'f' | 'n'

/** Definite nominative singular forms, keyed by gender. */
export type SerbianAdjective = Record<Gender, string>

export interface SerbianAnimal {
  /** Nominative singular. */
  word: string
  /** Grammatical gender (per srLex), not the natural one. */
  gender: Gender
}

export const SR_ADJECTIVES: readonly SerbianAdjective[] = [
  { m: 'brzi', f: 'brza', n: 'brzo' },
  { m: 'hrabri', f: 'hrabra', n: 'hrabro' },
  { m: 'veseli', f: 'vesela', n: 'veselo' },
  { m: 'mudri', f: 'mudra', n: 'mudro' },
  { m: 'vredni', f: 'vredna', n: 'vredno' },
  { m: 'nežni', f: 'nežna', n: 'nežno' },
  { m: 'snažni', f: 'snažna', n: 'snažno' },
  { m: 'smeli', f: 'smela', n: 'smelo' },
  { m: 'tihi', f: 'tiha', n: 'tiho' },
  { m: 'mirni', f: 'mirna', n: 'mirno' },
  { m: 'ljubazni', f: 'ljubazna', n: 'ljubazno' },
  { m: 'dobri', f: 'dobra', n: 'dobro' },
  { m: 'plemeniti', f: 'plemenita', n: 'plemenito' },
  { m: 'sjajni', f: 'sjajna', n: 'sjajno' },
  { m: 'zlatni', f: 'zlatna', n: 'zlatno' },
  { m: 'srebrni', f: 'srebrna', n: 'srebrno' },
  { m: 'plavi', f: 'plava', n: 'plavo' },
  { m: 'crveni', f: 'crvena', n: 'crveno' },
  { m: 'zeleni', f: 'zelena', n: 'zeleno' },
  { m: 'žuti', f: 'žuta', n: 'žuto' },
  { m: 'ljubičasti', f: 'ljubičasta', n: 'ljubičasto' },
  { m: 'narandžasti', f: 'narandžasta', n: 'narandžasto' },
  { m: 'ružičasti', f: 'ružičasta', n: 'ružičasto' },
  { m: 'beli', f: 'bela', n: 'belo' },
  { m: 'šareni', f: 'šarena', n: 'šareno' },
  { m: 'pegavi', f: 'pegava', n: 'pegavo' },
  { m: 'prugasti', f: 'prugasta', n: 'prugasto' },
  { m: 'čupavi', f: 'čupava', n: 'čupavo' },
  { m: 'pahuljasti', f: 'pahuljasta', n: 'pahuljasto' },
  { m: 'mekani', f: 'mekana', n: 'mekano' },
  { m: 'nasmejani', f: 'nasmejana', n: 'nasmejano' },
  { m: 'radoznali', f: 'radoznala', n: 'radoznalo' },
  { m: 'pametni', f: 'pametna', n: 'pametno' },
  { m: 'domišljati', f: 'domišljata', n: 'domišljato' },
  { m: 'lukavi', f: 'lukava', n: 'lukavo' },
  { m: 'vragolasti', f: 'vragolasta', n: 'vragolasto' },
  { m: 'nestašni', f: 'nestašna', n: 'nestašno' },
  { m: 'vedri', f: 'vedra', n: 'vedro' },
  { m: 'srećni', f: 'srećna', n: 'srećno' },
  { m: 'zadovoljni', f: 'zadovoljna', n: 'zadovoljno' },
  { m: 'ponosni', f: 'ponosna', n: 'ponosno' },
  { m: 'odvažni', f: 'odvažna', n: 'odvažno' },
  { m: 'neustrašivi', f: 'neustrašiva', n: 'neustrašivo' },
  { m: 'okretni', f: 'okretna', n: 'okretno' },
  { m: 'spretni', f: 'spretna', n: 'spretno' },
  { m: 'lagani', f: 'lagana', n: 'lagano' },
  { m: 'vitki', f: 'vitka', n: 'vitko' },
  { m: 'mali', f: 'mala', n: 'malo' },
  { m: 'veliki', f: 'velika', n: 'veliko' },
  { m: 'ogromni', f: 'ogromna', n: 'ogromno' },
  { m: 'sićušni', f: 'sićušna', n: 'sićušno' },
  { m: 'bucmasti', f: 'bucmasta', n: 'bucmasto' },
  { m: 'slatki', f: 'slatka', n: 'slatko' },
  { m: 'umiljati', f: 'umiljata', n: 'umiljato' },
  { m: 'dragi', f: 'draga', n: 'drago' },
  { m: 'divni', f: 'divna', n: 'divno' },
  { m: 'čarobni', f: 'čarobna', n: 'čarobno' },
  { m: 'tajanstveni', f: 'tajanstvena', n: 'tajanstveno' },
  { m: 'zamišljeni', f: 'zamišljena', n: 'zamišljeno' },
  { m: 'sanjivi', f: 'sanjiva', n: 'sanjivo' },
  { m: 'pospani', f: 'pospana', n: 'pospano' },
  { m: 'opušteni', f: 'opuštena', n: 'opušteno' },
  { m: 'strpljivi', f: 'strpljiva', n: 'strpljivo' },
  { m: 'uporni', f: 'uporna', n: 'uporno' },
  { m: 'marljivi', f: 'marljiva', n: 'marljivo' },
  { m: 'vešti', f: 'vešta', n: 'vešto' },
  { m: 'oštroumni', f: 'oštroumna', n: 'oštroumno' },
  { m: 'budni', f: 'budna', n: 'budno' },
  { m: 'oprezni', f: 'oprezna', n: 'oprezno' },
  { m: 'pažljivi', f: 'pažljiva', n: 'pažljivo' },
  { m: 'skromni', f: 'skromna', n: 'skromno' },
  { m: 'dostojanstveni', f: 'dostojanstvena', n: 'dostojanstveno' },
  { m: 'otmeni', f: 'otmena', n: 'otmeno' },
  { m: 'elegantni', f: 'elegantna', n: 'elegantno' },
  { m: 'gizdavi', f: 'gizdava', n: 'gizdavo' },
  { m: 'raspevani', f: 'raspevana', n: 'raspevano' },
  { m: 'razdragani', f: 'razdragana', n: 'razdragano' },
  { m: 'poletni', f: 'poletna', n: 'poletno' },
  { m: 'živahni', f: 'živahna', n: 'živahno' },
  { m: 'vatreni', f: 'vatrena', n: 'vatreno' },
  { m: 'ledeni', f: 'ledena', n: 'ledeno' },
  { m: 'sunčani', f: 'sunčana', n: 'sunčano' },
  { m: 'zvezdani', f: 'zvezdana', n: 'zvezdano' },
  { m: 'nebeski', f: 'nebeska', n: 'nebesko' },
  { m: 'šumski', f: 'šumska', n: 'šumsko' },
  { m: 'planinski', f: 'planinska', n: 'planinsko' },
  { m: 'divlji', f: 'divlja', n: 'divlje' },
  { m: 'pitomi', f: 'pitoma', n: 'pitomo' },
  { m: 'slobodni', f: 'slobodna', n: 'slobodno' },
  { m: 'gordi', f: 'gorda', n: 'gordo' },
  { m: 'junački', f: 'junačka', n: 'junačko' },
  { m: 'viteški', f: 'viteška', n: 'viteško' },
  { m: 'kraljevski', f: 'kraljevska', n: 'kraljevsko' },
  { m: 'carski', f: 'carska', n: 'carsko' },
  { m: 'drevni', f: 'drevna', n: 'drevno' },
  { m: 'mladi', f: 'mlada', n: 'mlado' },
  { m: 'tajni', f: 'tajna', n: 'tajno' },
  { m: 'nevidljivi', f: 'nevidljiva', n: 'nevidljivo' },
  { m: 'blistavi', f: 'blistava', n: 'blistavo' },
  { m: 'svetlucavi', f: 'svetlucava', n: 'svetlucavo' },
  { m: 'šaljivi', f: 'šaljiva', n: 'šaljivo' },
  { m: 'duhoviti', f: 'duhovita', n: 'duhovito' },
  { m: 'zabavni', f: 'zabavna', n: 'zabavno' },
  { m: 'simpatični', f: 'simpatična', n: 'simpatično' },
  { m: 'druželjubivi', f: 'druželjubiva', n: 'druželjubivo' },
  { m: 'gostoljubivi', f: 'gostoljubiva', n: 'gostoljubivo' },
  { m: 'darežljivi', f: 'darežljiva', n: 'darežljivo' },
  { m: 'velikodušni', f: 'velikodušna', n: 'velikodušno' },
  { m: 'iskreni', f: 'iskrena', n: 'iskreno' },
  { m: 'pošteni', f: 'poštena', n: 'pošteno' },
  { m: 'verni', f: 'verna', n: 'verno' },
  { m: 'odani', f: 'odana', n: 'odano' },
  { m: 'stameni', f: 'stamena', n: 'stameno' },
  { m: 'čvrsti', f: 'čvrsta', n: 'čvrsto' },
  { m: 'žilavi', f: 'žilava', n: 'žilavo' },
  { m: 'izdržljivi', f: 'izdržljiva', n: 'izdržljivo' },
  { m: 'neumorni', f: 'neumorna', n: 'neumorno' },
  { m: 'precizni', f: 'precizna', n: 'precizno' },
  { m: 'brižni', f: 'brižna', n: 'brižno' },
  { m: 'topli', f: 'topla', n: 'toplo' },
  { m: 'svilenkasti', f: 'svilenkasta', n: 'svilenkasto' },
  { m: 'baršunasti', f: 'baršunasta', n: 'baršunasto' },
  { m: 'kristalni', f: 'kristalna', n: 'kristalno' },
  { m: 'smaragdni', f: 'smaragdna', n: 'smaragdno' },
  { m: 'kosmički', f: 'kosmička', n: 'kosmičko' },
  { m: 'epski', f: 'epska', n: 'epsko' },
  { m: 'legendarni', f: 'legendarna', n: 'legendarno' },
  { m: 'slavni', f: 'slavna', n: 'slavno' },
  { m: 'čuveni', f: 'čuvena', n: 'čuveno' },
  { m: 'egzotični', f: 'egzotična', n: 'egzotično' },
  { m: 'polarni', f: 'polarna', n: 'polarno' },
  { m: 'veličanstveni', f: 'veličanstvena', n: 'veličanstveno' },
  { m: 'moćni', f: 'moćna', n: 'moćno' },
  { m: 'silni', f: 'silna', n: 'silno' },
  { m: 'munjeviti', f: 'munjevita', n: 'munjevito' },
  { m: 'hitri', f: 'hitra', n: 'hitro' },
  { m: 'žustri', f: 'žustra', n: 'žustro' },
  { m: 'energični', f: 'energična', n: 'energično' },
  { m: 'zaljubljeni', f: 'zaljubljena', n: 'zaljubljeno' },
  { m: 'romantični', f: 'romantična', n: 'romantično' },
  { m: 'nostalgični', f: 'nostalgična', n: 'nostalgično' },
  { m: 'filozofski', f: 'filozofska', n: 'filozofsko' },
  { m: 'učeni', f: 'učena', n: 'učeno' },
  { m: 'načitani', f: 'načitana', n: 'načitano' },
  { m: 'genijalni', f: 'genijalna', n: 'genijalno' },
  { m: 'kreativni', f: 'kreativna', n: 'kreativno' },
  { m: 'maštoviti', f: 'maštovita', n: 'maštovito' },
  { m: 'umetnički', f: 'umetnička', n: 'umetničko' },
  { m: 'muzikalni', f: 'muzikalna', n: 'muzikalno' },
  { m: 'ponoćni', f: 'ponoćna', n: 'ponoćno' },
  { m: 'jutarnji', f: 'jutarnja', n: 'jutarnje' },
  { m: 'večernji', f: 'večernja', n: 'večernje' },
  { m: 'prolećni', f: 'prolećna', n: 'prolećno' },
  { m: 'jesenji', f: 'jesenja', n: 'jesenje' },
  { m: 'zimski', f: 'zimska', n: 'zimsko' },
  { m: 'snežni', f: 'snežna', n: 'snežno' },
  { m: 'olujni', f: 'olujna', n: 'olujno' },
  { m: 'purpurni', f: 'purpurna', n: 'purpurno' },
  { m: 'tirkizni', f: 'tirkizna', n: 'tirkizno' },
  { m: 'bakarni', f: 'bakarna', n: 'bakarno' },
  { m: 'bronzani', f: 'bronzana', n: 'bronzano' },
  { m: 'gvozdeni', f: 'gvozdena', n: 'gvozdeno' },
  { m: 'čokoladni', f: 'čokoladna', n: 'čokoladno' },
  { m: 'medeni', f: 'medena', n: 'medeno' },
  { m: 'plišani', f: 'plišana', n: 'plišano' },
  { m: 'radosni', f: 'radosna', n: 'radosno' },
  { m: 'spokojni', f: 'spokojna', n: 'spokojno' },
  { m: 'staloženi', f: 'staložena', n: 'staloženo' },
  { m: 'hladnokrvni', f: 'hladnokrvna', n: 'hladnokrvno' },
  { m: 'nepobedivi', f: 'nepobediva', n: 'nepobedivo' },
  { m: 'vrhunski', f: 'vrhunska', n: 'vrhunsko' },
  { m: 'izvanredni', f: 'izvanredna', n: 'izvanredno' },
  { m: 'čudesni', f: 'čudesna', n: 'čudesno' },
  { m: 'fantastični', f: 'fantastična', n: 'fantastično' },
  { m: 'šašavi', f: 'šašava', n: 'šašavo' },
  { m: 'smešni', f: 'smešna', n: 'smešno' },
  { m: 'krilati', f: 'krilata', n: 'krilato' },
  { m: 'brkati', f: 'brkata', n: 'brkato' },
  { m: 'bradati', f: 'bradata', n: 'bradato' },
  { m: 'dugonogi', f: 'dugonoga', n: 'dugonogo' },
  { m: 'plavooki', f: 'plavooka', n: 'plavooko' },
]

export const SR_ANIMALS: readonly SerbianAnimal[] = [
  { word: 'vuk', gender: 'm' },
  { word: 'medved', gender: 'm' },
  { word: 'medo', gender: 'm' },
  { word: 'jež', gender: 'm' },
  { word: 'zec', gender: 'm' },
  { word: 'zečić', gender: 'm' },
  { word: 'kunić', gender: 'm' },
  { word: 'lav', gender: 'm' },
  { word: 'tigar', gender: 'm' },
  { word: 'leopard', gender: 'm' },
  { word: 'jaguar', gender: 'm' },
  { word: 'gepard', gender: 'm' },
  { word: 'ris', gender: 'm' },
  { word: 'jazavac', gender: 'm' },
  { word: 'dabar', gender: 'm' },
  { word: 'vidra', gender: 'f' },
  { word: 'hrčak', gender: 'm' },
  { word: 'miš', gender: 'm' },
  { word: 'pacov', gender: 'm' },
  { word: 'krtica', gender: 'f' },
  { word: 'jelen', gender: 'm' },
  { word: 'los', gender: 'm' },
  { word: 'bizon', gender: 'm' },
  { word: 'bivol', gender: 'm' },
  { word: 'konj', gender: 'm' },
  { word: 'kobila', gender: 'f' },
  { word: 'pastuv', gender: 'm' },
  { word: 'jarac', gender: 'm' },
  { word: 'ovan', gender: 'm' },
  { word: 'bik', gender: 'm' },
  { word: 'vepar', gender: 'm' },
  { word: 'majmun', gender: 'm' },
  { word: 'šimpanza', gender: 'm' },
  { word: 'gorila', gender: 'm' },
  { word: 'orangutan', gender: 'm' },
  { word: 'slon', gender: 'm' },
  { word: 'nosorog', gender: 'm' },
  { word: 'mamut', gender: 'm' },
  { word: 'kit', gender: 'm' },
  { word: 'delfin', gender: 'm' },
  { word: 'morž', gender: 'm' },
  { word: 'foka', gender: 'f' },
  { word: 'pingvin', gender: 'm' },
  { word: 'orao', gender: 'm' },
  { word: 'jastreb', gender: 'm' },
  { word: 'kondor', gender: 'm' },
  { word: 'albatros', gender: 'm' },
  { word: 'gavran', gender: 'm' },
  { word: 'vrabac', gender: 'm' },
  { word: 'golub', gender: 'm' },
  { word: 'labud', gender: 'm' },
  { word: 'paun', gender: 'm' },
  { word: 'pelikan', gender: 'm' },
  { word: 'flamingo', gender: 'm' },
  { word: 'papagaj', gender: 'm' },
  { word: 'kanarinac', gender: 'm' },
  { word: 'tukan', gender: 'm' },
  { word: 'kolibri', gender: 'm' },
  { word: 'detlić', gender: 'm' },
  { word: 'slavuj', gender: 'm' },
  { word: 'kos', gender: 'm' },
  { word: 'čvorak', gender: 'm' },
  { word: 'galeb', gender: 'm' },
  { word: 'ždral', gender: 'm' },
  { word: 'roda', gender: 'f' },
  { word: 'čaplja', gender: 'f' },
  { word: 'sova', gender: 'f' },
  { word: 'svraka', gender: 'f' },
  { word: 'vrana', gender: 'f' },
  { word: 'patka', gender: 'f' },
  { word: 'guska', gender: 'f' },
  { word: 'kokoška', gender: 'f' },
  { word: 'ćurka', gender: 'f' },
  { word: 'petao', gender: 'm' },
  { word: 'prepelica', gender: 'f' },
  { word: 'jarebica', gender: 'f' },
  { word: 'fazan', gender: 'm' },
  { word: 'noj', gender: 'm' },
  { word: 'kengur', gender: 'm' },
  { word: 'koala', gender: 'f' },
  { word: 'panda', gender: 'f' },
  { word: 'lemur', gender: 'm' },
  { word: 'lenjivac', gender: 'm' },
  { word: 'mravojed', gender: 'm' },
  { word: 'dikobraz', gender: 'm' },
  { word: 'tapir', gender: 'm' },
  { word: 'rakun', gender: 'm' },
  { word: 'tvor', gender: 'm' },
  { word: 'lasica', gender: 'f' },
  { word: 'kuna', gender: 'f' },
  { word: 'hermelin', gender: 'm' },
  { word: 'veverica', gender: 'f' },
  { word: 'puh', gender: 'm' },
  { word: 'mungos', gender: 'm' },
  { word: 'hijena', gender: 'f' },
  { word: 'šakal', gender: 'm' },
  { word: 'kojot', gender: 'm' },
  { word: 'lisica', gender: 'f' },
  { word: 'lisac', gender: 'm' },
  { word: 'puma', gender: 'f' },
  { word: 'pantera', gender: 'f' },
  { word: 'mačka', gender: 'f' },
  { word: 'mačor', gender: 'm' },
  { word: 'pas', gender: 'm' },
  { word: 'hrt', gender: 'm' },
  { word: 'kuče', gender: 'n' },
  { word: 'mače', gender: 'n' },
  { word: 'pile', gender: 'n' },
  { word: 'pače', gender: 'n' },
  { word: 'jagnje', gender: 'n' },
  { word: 'jare', gender: 'n' },
  { word: 'tele', gender: 'n' },
  { word: 'ždrebe', gender: 'n' },
  { word: 'prase', gender: 'n' },
  { word: 'magare', gender: 'n' },
  { word: 'lane', gender: 'n' },
  { word: 'mladunče', gender: 'n' },
  { word: 'krava', gender: 'f' },
  { word: 'koza', gender: 'f' },
  { word: 'ovca', gender: 'f' },
  { word: 'ovčica', gender: 'f' },
  { word: 'zebra', gender: 'f' },
  { word: 'žirafa', gender: 'f' },
  { word: 'antilopa', gender: 'f' },
  { word: 'gazela', gender: 'f' },
  { word: 'kamila', gender: 'f' },
  { word: 'alpaka', gender: 'f' },
  { word: 'irvas', gender: 'm' },
  { word: 'žaba', gender: 'f' },
  { word: 'krastača', gender: 'f' },
  { word: 'daždevnjak', gender: 'm' },
  { word: 'gušter', gender: 'm' },
  { word: 'kameleon', gender: 'm' },
  { word: 'iguana', gender: 'f' },
  { word: 'kornjača', gender: 'f' },
  { word: 'krokodil', gender: 'm' },
  { word: 'aligator', gender: 'm' },
  { word: 'zmija', gender: 'f' },
  { word: 'piton', gender: 'm' },
  { word: 'kobra', gender: 'f' },
  { word: 'poskok', gender: 'm' },
  { word: 'riba', gender: 'f' },
  { word: 'šaran', gender: 'm' },
  { word: 'štuka', gender: 'f' },
  { word: 'som', gender: 'm' },
  { word: 'pastrmka', gender: 'f' },
  { word: 'losos', gender: 'm' },
  { word: 'ajkula', gender: 'f' },
  { word: 'raža', gender: 'f' },
  { word: 'hobotnica', gender: 'f' },
  { word: 'lignja', gender: 'f' },
  { word: 'sipa', gender: 'f' },
  { word: 'jastog', gender: 'm' },
  { word: 'škamp', gender: 'm' },
  { word: 'meduza', gender: 'f' },
  { word: 'puž', gender: 'm' },
  { word: 'školjka', gender: 'f' },
  { word: 'pčela', gender: 'f' },
  { word: 'bumbar', gender: 'm' },
  { word: 'osa', gender: 'f' },
  { word: 'stršljen', gender: 'm' },
  { word: 'mrav', gender: 'm' },
  { word: 'leptir', gender: 'm' },
  { word: 'bubamara', gender: 'f' },
  { word: 'cvrčak', gender: 'm' },
  { word: 'skakavac', gender: 'm' },
  { word: 'svitac', gender: 'm' },
  { word: 'pauk', gender: 'm' },
  { word: 'škorpija', gender: 'f' },
  { word: 'gusenica', gender: 'f' },
  { word: 'glista', gender: 'f' },
  { word: 'zmaj', gender: 'm' },
  { word: 'jednorog', gender: 'm' },
  { word: 'feniks', gender: 'm' },
  { word: 'grifon', gender: 'm' },
]
